### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/tuya#59]
```
2020-05-24 21:08:26,473 ERROR    (Thread-18) [tuyaface.tuyaclient] (192.168.1.30) Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tuyaface/tuyaclient.py", line 151, in run
    result = command(*args)
  File "/usr/local/lib/python3.6/dist-packages/tuyaface/tuyaclient.py", line 173, in _status
    status_reply, all_replies = _status(self.device)
  File "/usr/local/lib/python3.6/dist-packages/tuyaface/__init__.py", line 246, in _status
    if cmd == tf.DP_QUERY and request_reply["data"] and request_reply["data"] != 'json obj data unvalid':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by emontnemery** [comment]
Do you still have this issue?

**Comment by TradeFace** [comment]
I didn't see it today. So, I'm not sure.
