### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by jkerdreux-imt** [TradeFace/tuya#64]
When someone toggle the lamp w/ the smart-life app, I get this. 

```
2020-05-27 23:05:12 i7 tuyaface.tuyaclient[98658] ERROR (192.168.1.176) Unexpected exception
Traceback (most recent call last):
  File "/home/jkx/tuya/tuyaface/tuyaclient.py", line 149, in run
    for reply in _process_raw_reply(self.device, data):
  File "/home/jkx/tuya/tuyaface/__init__.py", line 173, in _process_raw_reply
    payload = aescipher.decrypt(device["localkey"], data, False)
  File "/home/jkx/tuya/tuyaface/aescipher.py", line 22, in decrypt
    return _unpad(raw).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 3: invalid start byte
```

(I'm too busy to provide better debugging right now, I just push that here in case somebody can review it).

**Comment by TradeFace** [comment]
I can't make anything out of this. When you have the time please send a log. Thanks!

**Comment by emontnemery** [comment]
@jkerdreux-imt A log with log level set to DEBUG would be highly appreciated.

**Comment by jkerdreux-imt** [comment]
Ok, after a long session of debug.. I found my error. It was a typo in the localkey :( 

With the wrong key, the decrypt return some data but not something that is string-like, so unable to unpad / decode. I think the API should hide this error and raise something better. 

My first idea was to return None but this can have side effects in TuyaClient so I prefer to let to check instead of PR. 

Bye
